///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace PaintTest
{
    public partial class CatDrawing
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void DrawCat()
        {
        	repo.UntitledPaint.Home.Oval.Click();
        	Draw draw = new Draw(repo);
        	draw.drawSimpleFigure(500,200,780,400);
        	
        	
        	repo.UntitledPaint.Home.Line.Click();
        	draw.drawSimpleFigure(530,130,508,261);
        	draw.drawSimpleFigure(573,213,530,130);
        	draw.drawSimpleFigure(703,211,729,130);
        	draw.drawSimpleFigure(765,254,729,130);
        	
        	repo.UntitledPaint.Home.Oval.Click();
        	draw.drawSimpleFigure(538,248,612,282);
        	draw.drawSimpleFigure(656,248,730,282);
        	
        	repo.UntitledPaint.Home.Curve.Click();
        	draw.drawCurve(565,320,703,320,634,360);
        	
        	repo.UntitledPaint.Home.Triangle.Click();
        	draw.drawSimpleFigure(642,285,627,315);
        	
        	repo.UntitledPaint.Home.Diamond.Click();
        	draw.drawSimpleFigure(582,256,567,276);
        	draw.drawSimpleFigure(700,256,685,276);
        	//repo.UntitledPaint.Self.FindSingle<Ranorex.Unknown>("/form[@title='Untitled - Paint']/?/element[@Name='Using Oval tool on Canvas']").Click();
        }

    }
}
